apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: task-3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "cinder-zone-a"
